import "./globals.css";
// import { jetbrains_Mono } from "next/font/google";
import Header from "./components/ui/Header.jsx";
import PageTransition from "./components/ui/PageTransition";
import StairTransition from "./components/StairTransition";

// const jetbrainsMono = jetbrains_Mono({
//   subsets: ["latin"],
//   Weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
//   variable: "--font-jetbrainsMono",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
